// store/chat.types.ts

// Mutation Types
export const ADD_MESSAGE = 'ADD_MESSAGE'
export const UPDATE_MESSAGE = 'UPDATE_MESSAGE'
export const SET_REQUEST_PENDING = 'SET_REQUEST_PENDING'
export const SET_SYSTEM_MESSAGE = 'SET_SYSTEM_MESSAGE'
export const SET_CONTEXT_SIZE = 'SET_CONTEXT_SIZE'
export const SET_BATCH_SIZE = 'SET_BATCH_SIZE'
export const SET_UBATCH_SIZE = 'SET_UBATCH_SIZE'
export const SET_STATE_FROM_REQUEST = 'SET_STATE_FROM_REQUEST'
export const CLEAR_CHAT = 'CLEAR_CHAT'
export const SET_RNG_SEED = 'SET_RNG_SEED'
export const SET_TEMPERATURE = 'SET_TEMPERATURE'
export const DELETE_MESSAGE = 'DELETE_MESSAGE'
export const SET_DRY_BASE = 'SET_DRY_BASE'
export const SET_DRY_ALLOWED_LENGTH = 'SET_DRY_ALLOWED_LENGTH'
export const SET_DRY_MULTIPLIER = 'SET_DRY_MULTIPLIER'
export const SET_DRY_PENALTY_LAST_N = 'SET_DRY_PENALTY_LAST_N'
export const SET_DYNAMIC_TEMPERATURE = 'SET_DYNAMIC_TEMPERATURE'
export const SET_FREQ_PENALTY = 'SET_FREQ_PENALTY'
export const SET_MIN_P = 'SET_MIN_P'
export const SET_PENALTY_LAST_N = 'SET_PENALTY_LAST_N'
export const SET_REPEAT_PENALTY = 'SET_REPEAT_PENALTY'
export const SET_PRESENCE_PENALTY = 'SET_PRESENCE_PENALTY'

// Action Types
export const SET_DRY_ALLOWED_LENGTH_ACTION = 'setDryAllowedLength'
export const SET_DRY_BASE_ACTION = 'setDryBase'
export const SET_DRY_MULTIPLIER_ACTION = 'setDryMultiplier'
export const SET_DRY_PENALTY_LAST_N_ACTION = 'setDryPenaltyLastN'
export const SET_DYNAMIC_TEMPERATURE_ACTION = 'setDynamicTemperature'
export const SET_FREQ_PENALTY_ACTION = 'setFreqPenalty'
export const SET_MIN_P_ACTION = 'setMinP'
export const SET_PENALTY_LAST_N_ACTION = 'setPenaltyLastN'
export const SET_PRESENCE_PENALTY_ACTION = 'setPresencePenalty'
export const SET_REPEAT_PENALTY_ACTION = 'setRepeatPenalty'
export const SET_RNG_SEED_ACTION = 'setRngSeed'
export const SET_TEMPERATURE_ACTION = 'setTemperature'
export const DELETE_MESSAGE_ACTION = 'deleteMessage'
export const ADD_MESSAGE_ACTION = 'addMessage'
export const UPDATE_MESSAGE_ACTION = 'updateMessage'
export const SET_REQUEST_PENDING_ACTION = 'setRequestPending'
export const SET_SYSTEM_MESSAGE_ACTION = 'setSystemMessage'
export const SET_STATE_FROM_REQUEST_ACTION = 'setStateFromRequest'
export const SET_CONTEXT_SIZE_ACTION = 'setContextSize'
export const SET_BATCH_SIZE_ACTION = 'setBatchSize'
export const SET_UBATCH_SIZE_ACTION = 'setUBatchSize'
export const CLEAR_CHAT_ACTION = 'clearChat'
